void cmd_send_prep(char *cmd, int len, obj *o);
void cmd_send_hello(obj *o);
void cmd_send_iam(obj *o);
void cmd_send_hui(obj *o);
void cmd_send_newp(obj *o);
void cmd_send_obj(obj *no,obj *so);
void cmd_send_dobj(obj *no,obj *so);
void cmd_send_mv(obj *no,obj *so);
void cmd_send_mymv(obj *o);
void cmd_send_obj_loc(obj *o,lnk *ol);
void cmd_send_mv_loc(obj *o,lnk *ol);
void cmd_send_dobj_loc(obj *o,lnk *ol);
void cmd_send_prich(obj *o,obj *so);
void cmd_send_chat(obj *o,char *txt);
void cmd_send_chat_broadcast(obj *o, char *txt);
void cmd_send_bl_begin(obj *o);
void cmd_send_bl_begin1(obj *o);
void cmd_send_buse(obj *bo, char *cmd, int len);
void cmd_send_bl_update(obj *fo);
void cmd_send_myobj_loc(obj *o,lnk *ol);
void cmd_send_pobj_dobj(obj *o);
void cmd_send_pobj_obj(obj *o,obj *so);
void cmd_send_mnt(obj *o,obj *mo);
